version: '3.8'

services:
  redis:
    image: redis:alpine
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 core.wsgi:application
    volumes:
      - .:/app  # Mount the current directory for code changes
      - ./staticfiles:/app/staticfiles  # Ensure Nginx can access collected static files
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
    ports:
      - "8000:8000"  # Make web accessible on port 8000 for internal proxying

networks:
  backend:
