# Generated by Django 5.1.2 on 2024-10-27 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenericName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, default='default_logo.jpg', upload_to='manufacturer_images/')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category_type', models.CharField(choices=[('ANT', 'Antibiotic'), ('ANL', 'Analgesic'), ('APR', 'Antipyretic'), ('VIT', 'Vitamin'), ('SUP', 'Supplement'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('image', models.ImageField(blank=True, default='default_image.jpg', upload_to='category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('TBL', 'Tablet'), ('SYR', 'Syrup'), ('INJ', 'Injection'), ('ONT', 'Ointment'), ('DRP', 'Drops'), ('OTH', 'Other')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TherapeuticClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subclass_name', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('name', 'subclass_name')},
            },
        ),
        migrations.CreateModel(
            name='MedicineDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('unit_of_measurement', models.CharField(choices=[('TBL', 'Tablet'), ('CAP', 'Capsule'), ('SYR', 'Syrup'), ('ONT', 'Ointment'), ('OTH', 'Other')], default='TBL', max_length=3)),
                ('prescription_required', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='inventory.medicinecategory')),
                ('conditions', models.ManyToManyField(blank=True, related_name='medications', to='inventory.condition')),
                ('generic_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='inventory.genericname')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='inventory.manufacturer')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='inventory.medicineform')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'batch_number')},
            },
        ),
    ]
