# Generated by Django 5.1.2 on 2024-10-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicinedetail",
            name="search_content",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.RunSQL(
            """
            ALTER TABLE inventory_medicinedetail
            ADD FULLTEXT INDEX search_content_idx (search_content);
            """,
            reverse_sql="""
            ALTER TABLE inventory_medicinedetail
            DROP INDEX search_content_idx;
            """,
        ),
    ]
